version: '3'
services:
  synology-dev-env:
    container_name: synology-dev-env
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: unless-stopped
    volumes:
      - synology-dev-data:/data
      - ./templates:/data/templates

volumes:
  synology-dev-data:
    name: synology-dev-data

